/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/'
      | '/admin/books'
      | '/admin/chapters'
      | '/admin/contents'
      | '/admin/labels'
      | '/admin/users'
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/books': RouteRecordInfo<
      '/admin/books',
      '/admin/books',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/chapters': RouteRecordInfo<
      '/admin/chapters',
      '/admin/chapters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/contents': RouteRecordInfo<
      '/admin/contents',
      '/admin/contents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/labels': RouteRecordInfo<
      '/admin/labels',
      '/admin/labels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/chapters': RouteRecordInfo<
      '/home/chapters',
      '/home/chapters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/contents': RouteRecordInfo<
      '/home/contents',
      '/home/contents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/'
        | '/admin/books'
        | '/admin/chapters'
        | '/admin/contents'
        | '/admin/labels'
        | '/admin/users'
      views:
        | 'default'
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/books.vue': {
      routes:
        | '/admin/books'
      views:
        | never
    }
    'src/pages/admin/chapters.vue': {
      routes:
        | '/admin/chapters'
      views:
        | never
    }
    'src/pages/admin/contents.vue': {
      routes:
        | '/admin/contents'
      views:
        | never
    }
    'src/pages/admin/labels.vue': {
      routes:
        | '/admin/labels'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/home/chapters.vue': {
      routes:
        | '/home/chapters'
      views:
        | never
    }
    'src/pages/home/contents.vue': {
      routes:
        | '/home/contents'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
